apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-cwln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-cwln
    app.kubernetes.io/part-of: test-annotations-app-rjww
  name: test-annotations-cwln
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-cwln
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-cwln
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-ojio-tenant/test-annotations-app-rjww/test-annotations-cwln@sha256:4d7832a3feda526c4879036ebc455a3118d47d8573c55ced806b98c5ef45a9ce
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
